--USER TABLE
--""로 키워드를 그냥 문자열로 변경해준다
--핸드폰 번호를 숫자타입으로 저장하면 맨앞 0을 지운다
--웹에서 왠만한 데이터는 문자열로 저장하니까 VARCHAR 이용하는게 좋다
--CLOB BLOB : 게시글같은거 저장할때 (VARCHAR2로 처리하기엔 너무 큰 데이터)
CREATE TABLE "USER" (
ID VARCHAR2(20) PRIMARY KEY,
NAME VARCHAR2(20),
PHONE VARCHAR2(11),
ADDRESS VARCHAR2(200)
);

DROP TABLE "USER";
--ID VARCHAR2(20) PRIMARY KEY -> PRIMARY KEY의 이름이 임의로 만들어지므로 CONSTRAINT 이용
CREATE TABLE "USER"(
ID VARCHAR2(20),
NAME VARCHAR2(20),
PHONE VARCHAR2(11),
ADDRESS VARCHAR2(200),
CONSTRAINT PK_USER PRIMARY KEY(ID)
);

ALTER TABLE "USER" RENAME TO MEMBER;
ALTER TABLE MEMBER RENAME COLUMN ID TO USERID;
ALTER TABLE MEMBER ADD PASSWORD VARCHAR2(20);
ALTER TABLE MEMBER MODIFY (
NAME VARCHAR2(30)
);
ALTER TABLE MEMBER DROP COLUMN PASSWORD;
ALTER TABLE MEMBER DROP CONSTRAINT PK_USER;
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY(USERID);

--영화테이블
--영화의 배우는 많다 '표지훈,유승호,김하늘,박보검' 식으로 저장한다
--CHECK(OPENDATE >= TO_DATE('2000-01-01','yyyy-MM-DD')) -> '2000-01-01'의 년월일을 지정해주고 DATE타입으로 변경한 후 조건검사한다
CREATE TABLE MOVIE(
TITLE VARCHAR2(100),
DIRECTOR VARCHAR2(20),
GENRE VARCHAR2(20),
ACTOR VARCHAR2(300),
OPENDATE DATE CHECK(OPENDATE >= TO_DATE('2000-01-01','yyyy-MM-DD')),
SCORE NUMBER(2,1)
);
