--NULL 처리함수
--PLAYER 테이블에서 선수이름, 키, 몸무게(NULL이면 '미등록')
--한 컬럼에 여러 데이터 타입을 사용할 수 없으므로 함수를 이용해 데이터 타입을 변경해야한다
SELECT 
   PLAYER_NAME 이름,
   NVL(TO_CHAR(HEIGHT),'미등록') 키,
   NVL(TO_CHAR(WEIGHT),'미등록') 몸무게
FROM PLAYER;
SELECT 
   PLAYER_NAME 이름,
   NVL2(HEIGHT,TO_CHAR(HEIGHT),'미등록') 키,
   NVL2(WEIGHT,TO_CHAR(HEIGHT),'미등록') 몸무게
FROM PLAYER;
SELECT 
   PLAYER_NAME 이름,
   CASE
      WHEN HEIGHT IS NULL THEN '미등록'
      ELSE TO_CHAR(HEIGHT)
    END 키,
    CASE
      WHEN WEIGHT IS NULL THEN '미등록'
      ELSE TO_CHAR(WEIGHT)
    END 몸무게   
FROM PLAYER;
--PLAYER 테이블에서 POSITION 검색
--POSITION이 NULL이면 미정으로 출력
SELECT
   PLAYER_NAME 선수이름,
   NVL(POSITION,'미정') 포지션
FROM PLAYER;
--PLAYER 테이블에서 이름 별명 검색
--별명이 NULL이면 이름만 나오게 출력
SELECT
   NVL2(NICKNAME,PLAYER_NAME || '-' || NICKNAME,PLAYER_NAME) "PLAYER"
FROM PLAYER;

--CONCAT()
SELECT CONCAT('FLO','WER') FROM DUAL;
SELECT CONCAT(PLAYER_NAME,' : ' || NICKNAME) FROM PLAYER;

--UPPER LOWER INITCAP
SELECT UPPER('korea') FROM DUAL;
SELECT LOWER('KOREA') FROM DUAL;
SELECT INITCAP('KOREA') FROM DUAL;

--LENGTH LENGTHB
SELECT LENGTH('정서빈') FROM DUAL;
SELECT LENGTHB('정서빈') FROM DUAL;
--PLAYER 테이블에서 이름이 2글자인 선수 검색
SELECT * FROM PLAYER WHERE LENGTH(PLAYER_NAME) = 2;

--SUBSTR
--T_STUDENT에서 1전공이 101번인 학생의 이름 생년월일 출력
SELECT
   NAME 학생이름,
   SUBSTR(JUMIN,1,6) 생년월일
FROM T_STUDENT
WHERE DEPTNO1 = '101';
--T_STUDENT에서 8월생의 이름 생년월일 출력
SELECT
   NAME 학생이름,
   SUBSTR(JUMIN,1,6) 생년월일
FROM T_STUDENT
WHERE SUBSTR(JUMIN,3,2) = '08';
--T_STUDEBT 에서 여학생의 이름 주민번호 출력
SELECT
   NAME 학생이름,
   JUMIN 주민반호
FROM T_STUDENT
WHERE SUBSTR(JUMIN,7,1) = '2';

--INSTRING
SELECT INSTR('A*B*C','*',1,2) FROM DUAL;

--LPAD RPAD
SELECT LPAD('ABCD',10,'*') FROM DUAL;
SELECT RPAD('ABCD',10,'*') FROM DUAL;
--주민번호 뒺자리 숨김
SELECT RPAD(SUBSTR('9811011234567',1,6),13,'*') FROM DUAL;
--T_STUDENT 테이블에서 1전공이 101번인 학생의 ID를 총 10글자로 채워서 검색 (빈자리는 아무 기호)
SELECT RPAD(ID,10,'*') FROM T_STUDENT WHETE DEPTNO1 = 101;

--REPLACE
SELECT REPLACE('슈퍼맨, 슈퍼우먼','슈퍼','SUPER') FROM DUAL;
--PLAYER 테이블에서 선수들의 이름을 성부분만 #으로 바꿔서 출력
SELECT REPLACE(PLAYER_NAME,SUBSTR(PLAYER_NAME,1,1),'#') FROM PLAYER;
--T_STUDENT 테이블에서 102번 학과의 학생들의 이름 ,전화번호를 출력하되 전화번호는 02-###-2807로 출력
SELECT
   NAME 이름,
   DEPTNO1 학과번호,
   REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,')') + 1,INSTR(TEL,'-') - INSTR(TEL,')') - 1),"***") 전화번호
FORM T_STUDENT
WHERE DEPTNO1 = 102;

--숫자함수
SELECT ABS(-10) FROM DUAL;
SELECT MOD(10,3) FROM DUAL;
SELECT CEIL(3.14),CEIL(-3.14) FROM DUAL;
SELECT FLOOR(3.14), FLOOR(-3.14) FROM DUAL;
SELECT ROUND(3.4564574), ROUND(3.8564543) FROM DUAL;
--소수 2째자리까지 나타내라 -> 소수 3째자리에서 반올림
SELECT ROUND(3.1414214,2) FROM DUAL;
--두번쨰 인수에 음수를 넣으면 정수부분에서 반올림 
SELECT ROUND(3288.1141421,-2) FROM DUAL;
SELECT TRUNC(3.9),TRUNC(-3.9) FROM DUAL;
SELECT POWER(3,2) FROM DUAL;
--루트
SELECT POWER(2,POWER(2,-1)) FROM DUAL;

--날짜함수
--내일
SELECT SYSDATE + 1 FROM DUAL;
--1시간 뒤
SELECT SYSDATE + 1/24 FROM DUAL;
--정오를 기준으로 반올림
SELECT ROUND(SYSDATE) FROM DUAL;
--시간 버림
SELECT TRUNC(SYSDATE) FROM DUAL;
--개월 차이
SELECT TRUNC(MONTHS_BETWEEN(TO_DATE('11-21-1995','MM-DD-YYYY'), TO_DATE('12-21-1995','MM-DD-YYYY'))) FROM DUAL;
--T_PROFESSOR 테이블에서 오늘을 기준으로 근속년수 근속개월 근속일을 계산하여 풀력
--근속 개월 근속 일은 소수점 1자리
SELECT
   NAME 이름,
   TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12) 근속연수,
   ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE),1) 근속개월,
   ROUND(SYSDATE-HIREDATE,1) 근속일수   
FROM T_PROFESSOR;
--이번 달의 마지막 날짜
SELECT LAST_DAY(SYSDATE) FROM DUAL;

--그룹함수
SELECT COUNT(PLAYER_NAME) FROM PLAYER;
SELECT AVG(HEIGHT),MAX(HEIGHT),MIN(HEIGHT),SUM(HEIGHT) FROM PLAYER;